/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.programacion;

/**
 *
 * @author AlbertoManuel
 */
public class ventanaPpal extends javax.swing.JFrame {

    /**
     * Creates new form ventanaPpal
     */
    public ventanaPpal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        panelPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAlumnos = new javax.swing.JMenu();
        menuAñadirAlum = new javax.swing.JMenuItem();
        menuModificarAlum = new javax.swing.JMenuItem();
        menuEliminarAlum = new javax.swing.JMenuItem();
        menuListarAlum = new javax.swing.JMenuItem();
        menuDocentes = new javax.swing.JMenu();
        menuAñadirDoc = new javax.swing.JMenuItem();
        menuModificarDoc = new javax.swing.JMenuItem();
        menuEliminarDoc = new javax.swing.JMenuItem();
        menuListarDoc = new javax.swing.JMenuItem();
        menuCursos = new javax.swing.JMenu();
        menuAñadirCursos = new javax.swing.JMenuItem();
        menuModificarCursos = new javax.swing.JMenuItem();
        menuEliminarCursos = new javax.swing.JMenuItem();
        menuListarCursos = new javax.swing.JMenuItem();
        menuAulas = new javax.swing.JMenu();
        menuAñadirAulas = new javax.swing.JMenuItem();
        menuModificarAulas = new javax.swing.JMenuItem();
        menuEliminarAulas = new javax.swing.JMenuItem();
        menuListarAulas = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Añadir");

        jButton2.setText("Modificar");

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Buscar");

        jRadioButton1.setText("jRadioButton1");

        jRadioButton2.setText("jRadioButton2");

        jRadioButton3.setText("jRadioButton3");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)))
        );

        menuAlumnos.setText("Alumnos");

        menuAñadirAlum.setText("Añadir");
        menuAñadirAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAñadirAlumActionPerformed(evt);
            }
        });
        menuAlumnos.add(menuAñadirAlum);

        menuModificarAlum.setText("Modificar");
        menuAlumnos.add(menuModificarAlum);

        menuEliminarAlum.setText("Eliminar");
        menuAlumnos.add(menuEliminarAlum);

        menuListarAlum.setText("Listar");
        menuAlumnos.add(menuListarAlum);

        jMenuBar1.add(menuAlumnos);

        menuDocentes.setText("Docentes");

        menuAñadirDoc.setText("Añadir");
        menuAñadirDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAñadirDocActionPerformed(evt);
            }
        });
        menuDocentes.add(menuAñadirDoc);

        menuModificarDoc.setText("Modificar");
        menuDocentes.add(menuModificarDoc);

        menuEliminarDoc.setText("Eliminar");
        menuDocentes.add(menuEliminarDoc);

        menuListarDoc.setText("Listar");
        menuDocentes.add(menuListarDoc);

        jMenuBar1.add(menuDocentes);

        menuCursos.setText("Cursos");

        menuAñadirCursos.setText("Añadir");
        menuAñadirCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAñadirCursosActionPerformed(evt);
            }
        });
        menuCursos.add(menuAñadirCursos);

        menuModificarCursos.setText("Modificar");
        menuCursos.add(menuModificarCursos);

        menuEliminarCursos.setText("Eliminar");
        menuCursos.add(menuEliminarCursos);

        menuListarCursos.setText("Listar");
        menuCursos.add(menuListarCursos);

        jMenuBar1.add(menuCursos);

        menuAulas.setText("Aulas");

        menuAñadirAulas.setText("Añadir");
        menuAñadirAulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAñadirAulasActionPerformed(evt);
            }
        });
        menuAulas.add(menuAñadirAulas);

        menuModificarAulas.setText("Modificar");
        menuAulas.add(menuModificarAulas);

        menuEliminarAulas.setText("Eliminar");
        menuAulas.add(menuEliminarAulas);

        menuListarAulas.setText("Listar");
        menuAulas.add(menuListarAulas);

        jMenuBar1.add(menuAulas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAñadirAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAñadirAlumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAñadirAlumActionPerformed

    private void menuAñadirDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAñadirDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAñadirDocActionPerformed

    private void menuAñadirCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAñadirCursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAñadirCursosActionPerformed

    private void menuAñadirAulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAñadirAulasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAñadirAulasActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaPpal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenu menuAlumnos;
    private javax.swing.JMenu menuAulas;
    private javax.swing.JMenuItem menuAñadirAlum;
    private javax.swing.JMenuItem menuAñadirAulas;
    private javax.swing.JMenuItem menuAñadirCursos;
    private javax.swing.JMenuItem menuAñadirDoc;
    private javax.swing.JMenu menuCursos;
    private javax.swing.JMenu menuDocentes;
    private javax.swing.JMenuItem menuEliminarAlum;
    private javax.swing.JMenuItem menuEliminarAulas;
    private javax.swing.JMenuItem menuEliminarCursos;
    private javax.swing.JMenuItem menuEliminarDoc;
    private javax.swing.JMenuItem menuListarAlum;
    private javax.swing.JMenuItem menuListarAulas;
    private javax.swing.JMenuItem menuListarCursos;
    private javax.swing.JMenuItem menuListarDoc;
    private javax.swing.JMenuItem menuModificarAlum;
    private javax.swing.JMenuItem menuModificarAulas;
    private javax.swing.JMenuItem menuModificarCursos;
    private javax.swing.JMenuItem menuModificarDoc;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
